log:
  level: WARN

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
            
  websecure:
    address: :443

certificatesResolvers:
  letsEncrypt:
    acme:
      email: ahmedhussiien@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

tls:
  options:
    myTLSOptions:
      minVersion: VersionTLS12

providers:
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik_proxy
